# Simple workflow for deploying a specific HTML file to GitHub Pages
name: Deploy player3.html to Pages

on:
  # Runs on pushes targeting the default branch (replace with 'main' or 'master' as needed)
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout
        uses: actions/checkout@v4
      
      # Step 2: Setup GitHub Pages environment
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      # Step 3: Upload the specific HTML file (player3.html)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Specify the path to the HTML file (player3.html in the root directory)
          path: 'main/player3.html'
      
      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
